loading Roboflow workspace...
Traceback (most recent call last):
  File "/Users/om/YOLOv8 training/src/train.py", line 49, in <module>
    main()
  File "/Users/om/YOLOv8 training/src/train.py", line 29, in main
    download_dataset()
  File "/Users/om/YOLOv8 training/src/train.py", line 23, in download_dataset
    project = rf.workspace("YOLOv8").project("aquarium-data-cots")
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/om/YOLOv8 training/fresh_yolo_env/lib/python3.12/site-packages/roboflow/__init__.py", line 243, in workspace
    list_projects = rfapi.get_workspace(api_key, the_workspace)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/om/YOLOv8 training/fresh_yolo_env/lib/python3.12/site-packages/roboflow/adapters/rfapi.py", line 36, in get_workspace
    raise RoboflowError(response.text)
roboflow.adapters.rfapi.RoboflowError: {
    "error": {
        "message": "Unsupported get request. Workspace with ID \"YOLOv8\" does not exist or cannot be loaded due to missing permissions.",
        "status": 404,
        "type": "GraphMethodException",
        "hint": "You can see your available workspaces by issuing a GET request to /workspaces"
    }
}
